/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface VikybAmbulanceWlList {
    }
}
declare global {
    interface HTMLVikybAmbulanceWlListElement extends Components.VikybAmbulanceWlList, HTMLStencilElement {
    }
    var HTMLVikybAmbulanceWlListElement: {
        prototype: HTMLVikybAmbulanceWlListElement;
        new (): HTMLVikybAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "vikyb-ambulance-wl-list": HTMLVikybAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface VikybAmbulanceWlList {
    }
    interface IntrinsicElements {
        "vikyb-ambulance-wl-list": VikybAmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "vikyb-ambulance-wl-list": LocalJSX.IntrinsicElements["vikyb-ambulance-wl-list"] & JSXBase.HTMLAttributes<HTMLVikybAmbulanceWlListElement>;
        }
    }
}
